export const STORE_PETS = 'STORE_PETS';
export const LOCAL_PET_REMOVAL = 'LOCAL_PET_REMOVAL';
export const SORT_PETS = 'SORT_PETS'

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCEED = 'AUTH_SUCCEED';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_ERR_REMOVED = 'AUTH_ERR_REMOVED';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADD_NEW_PET_START = 'ADD_NEW_PET_START';
export const ADD_NEW_PET_SUCCEED = 'ADD_NEW_PET_SUCCEED';
export const ADD_NEW_PET_FAILED = 'ADD_NEW_PET_FAILED';

export const FETCH_USER_PETS = 'FETCH_USER_PETS';

export const LIKE_PET_UPDATE = 'LIKE_PET_UPDATE';

